name: Scheduled Python Script

on:
  schedule:
    # Schedule for March 1 to May 31 (3-5 Months) 每天18点
    - cron: '25 21 * 4 *'  # Everyday in April
    - cron: '25 21 * 5 *'  # Everyday in May
    - cron: '25 21 * 6 *'  # Everyday in June
    # Schedule for September 1 to November 30 (9-11 Months) 每天18点
    - cron: '25 21 * 9 *'  # Everyday in September
    - cron: '25 21 * 10 *' # Everyday in October
    - cron: '25 21 * 11 *' # Everyday in November

jobs:
  run-main-py:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run Python Script
      run: python ./main.py
