name: Python application

on:
  schedule:
    - cron: '0 1 * 4-6 *'  # 每年四、五、六月每天的 1:00 UTC 执行（北京时间 9:00）
    - cron: '0 1 * 10-12 *' # 每年十、十一、十二月每天的 1:00 UTC 执行（北京时间 9:00）

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run LoveSport
        run: python ./main.py
